spring:
  application:
    name: JSystems-SilkyCodders-1
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: gemma3:12b
          temperature: 0.7
    vertexai:
      gemini:
        enabled: false
  web:
    cors:
      allowed-origins: http://localhost:5173
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      allow-credentials: true

server:
  port: 8080
